#!/usr/bin/env bash
# configures an Nginx server to listen on port 80

# remove the default Nginx configuration file
rm/etc/nginx/sites-enabled/default
# configure Nginx to listen on port 80 IPv4 IPs
ln -s/etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx
service nginx restart
