#!/usr/bin/env bash
# configures an Nginx service to listen to port 80

# creates a symbolic link (-s option) between the
# Nginx configuration file and enabled site dir
ln -sf/etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# restart nginx
service nginx start
# terminates the first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
